name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou la branche de ton choix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (si tu utilises Node.js, sinon, ignore cette étape)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build the site (si nécessaire, dépend de ton projet)
      run: npm run build  # Modifie cette commande si tu utilises un autre outil

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Déploiement sur la branche gh-pages
        folder: build  # Le dossier à déployer (généralement "build" ou "dist" selon ton projet)
